// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU3uhGT1fNMzSBVtUpxB5nzGdxJ8bfMLI',
    appId: '1:802154487664:web:d64f72d19efce723feb9b5',
    messagingSenderId: '802154487664',
    projectId: 'mymoneyapp-5098a',
    authDomain: 'mymoneyapp-5098a.firebaseapp.com',
    storageBucket: 'mymoneyapp-5098a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbm_MiuvvZYZB0WIz9A1wMHKe0BYlwhI',
    appId: '1:802154487664:android:a215e4b685fbbf03feb9b5',
    messagingSenderId: '802154487664',
    projectId: 'mymoneyapp-5098a',
    storageBucket: 'mymoneyapp-5098a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZN-PXqijqj-3rT57O97R42CvP-QC3hwg',
    appId: '1:802154487664:ios:8880805e299d239dfeb9b5',
    messagingSenderId: '802154487664',
    projectId: 'mymoneyapp-5098a',
    storageBucket: 'mymoneyapp-5098a.appspot.com',
    iosClientId: '802154487664-timcjlraj3rv2mtpnkheueogdafnc4ts.apps.googleusercontent.com',
    iosBundleId: 'co',
  );
}
