// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxiqA6UxXGJZ8tgTzNiR9BNEpVi-bPkQ',
    appId: '1:992143873823:web:85fe6e5ac8da104a35022a',
    messagingSenderId: '992143873823',
    projectId: 'tzuzul-code-2d2f8',
    authDomain: 'tzuzul-code-2d2f8.firebaseapp.com',
    databaseURL: 'https://tzuzul-code-2d2f8-default-rtdb.firebaseio.com',
    storageBucket: 'tzuzul-code-2d2f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdM4axQMJDlnOr4PmCPhMZif5HJjsbf0',
    appId: '1:992143873823:android:13a97751c4eb332e35022a',
    messagingSenderId: '992143873823',
    projectId: 'tzuzul-code-2d2f8',
    databaseURL: 'https://tzuzul-code-2d2f8-default-rtdb.firebaseio.com',
    storageBucket: 'tzuzul-code-2d2f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZXELoIrFx0kDpTPk15Hu8Lh-5NrQYgHU',
    appId: '1:992143873823:ios:013bb9317918e39735022a',
    messagingSenderId: '992143873823',
    projectId: 'tzuzul-code-2d2f8',
    databaseURL: 'https://tzuzul-code-2d2f8-default-rtdb.firebaseio.com',
    storageBucket: 'tzuzul-code-2d2f8.appspot.com',
    iosClientId: '992143873823-lumrq1j51q88chqc58a93o5punm1sucl.apps.googleusercontent.com',
    iosBundleId: 'co',
  );
}
